[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/1E11gexPQvAPi9IWFtaoOahELhDE_dQl5/view?usp=sharing"
  status = 301
  force = true
  
[[redirects]]
  from = "/blog"
  to = "/blog_index.html"
  status = 200
  force = true
