# This is a basic workflow to help you get started with Actions

name: Pandoc build site

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      results-file: "./site/"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: checkout repo content
       uses: actions/checkout@v2 # checkout the repository content to github runner.
     - name: setup pandoc
       uses: r-lib/actions/setup-pandoc@v1
       with:
         pandoc-version: '2.11.4'
     - name: setup python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8 #install the python needed
     - name: execute python blog script
       run: |
         python blog.py
     - name: Commit changes
       uses: EndBug/add-and-commit@v7
       with:
        author_name: Ben Boyle
        author_email: me@benboyle.ca
        message: 'Built site'
        add: './site/*'
        push: true

